# Generated by Django 3.2.25 on 2024-05-20 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(default='Running', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=260)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
